# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from interfaces.grpc.proto import models_pb2 as proto_dot_models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/auth.proto\x12\x07twittpy\x1a\x12proto/models.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\",\n\rSignUpRequest\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.twittpy.User\"\x10\n\x0eSignUpResponse2y\n\x04\x41uth\x12\x36\n\x05Login\x12\x15.twittpy.LoginRequest\x1a\x16.twittpy.LoginResponse\x12\x39\n\x06SignUp\x12\x16.twittpy.SignUpRequest\x1a\x17.twittpy.SignUpResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=49
  _globals['_LOGINREQUEST']._serialized_end=99
  _globals['_LOGINRESPONSE']._serialized_start=101
  _globals['_LOGINRESPONSE']._serialized_end=131
  _globals['_SIGNUPREQUEST']._serialized_start=133
  _globals['_SIGNUPREQUEST']._serialized_end=177
  _globals['_SIGNUPRESPONSE']._serialized_start=179
  _globals['_SIGNUPRESPONSE']._serialized_end=195
  _globals['_AUTH']._serialized_start=197
  _globals['_AUTH']._serialized_end=318
# @@protoc_insertion_point(module_scope)
