# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/users.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/users.proto\x12\x07twittpy\x1a\x12proto/models.proto\"\"\n\x0eGetUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\".\n\x0fGetUserResponse\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.twittpy.User\".\n\x0f\x45\x64itUserRequest\x12\x1b\n\x04user\x18\x01 \x01(\x0b\x32\r.twittpy.User\"\x12\n\x10\x45\x64itUserResponse2\x90\x01\n\x0bUserService\x12>\n\x07GetUser\x12\x17.twittpy.GetUserRequest\x1a\x18.twittpy.GetUserResponse\"\x00\x12\x41\n\x08\x45\x64itUser\x12\x18.twittpy.EditUserRequest\x1a\x19.twittpy.EditUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERREQUEST']._serialized_start=50
  _globals['_GETUSERREQUEST']._serialized_end=84
  _globals['_GETUSERRESPONSE']._serialized_start=86
  _globals['_GETUSERRESPONSE']._serialized_end=132
  _globals['_EDITUSERREQUEST']._serialized_start=134
  _globals['_EDITUSERREQUEST']._serialized_end=180
  _globals['_EDITUSERRESPONSE']._serialized_start=182
  _globals['_EDITUSERRESPONSE']._serialized_end=200
  _globals['_USERSERVICE']._serialized_start=203
  _globals['_USERSERVICE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
