# Operation codes
FIND_SUCCESSOR = 1
FIND_PREDECESSOR = 2
GET_SUCCESSOR = 3
GET_PREDECESSOR = 4
NOTIFY = 5
CHECK_PREDECESSOR = 6
CLOSEST_PRECEDING_FINGER = 7
STORE_KEY = 8
RETRIEVE_KEY = 9
DELETE_KEY = 10
PING = 11
PING_LEADER = 12
ELECTION = 13
GET_SUCCESSOR_AND_NOTIFY = 14
SET_PARTITION = 15
RESOLVE_DATA = 16

# Booleans
FALSE = 0
TRUE = 1

# Messages
ALIVE = 'Im alive'
ARE_YOU = 'Are you a chord?'
YES_IM = 'Yes, I am a chord'
EMPTY = ''