# Operation codes
FIND_SUCCESSOR = 1
FIND_PREDECESSOR = 2
GET_SUCCESSOR = 3
GET_PREDECESSOR = 4
NOTIFY = 5
CHECK_PREDECESSOR = 6
CLOSEST_PRECEDING_FINGER = 7
STORE_KEY = 8
RETRIEVE_KEY = 9
DELETE_KEY = 10
PING = 11
STOP_DISCOVERING = 12
JOIN = 13
PING_LEADER = 14
ELECTION = 15

# Booleans
FALSE = 0
TRUE = 1

# Messages
ALIVE = 'Im alive'